name: "Swift Unidoc"
description: "Validate Swift documentation using Unidoc"

inputs:
    unidoc-version:
        description: "The version of Unidoc to use"
        required: true
        default: "0.19.0"

runs:
    using: composite
    steps:
        -   name: Cache Unidoc
            uses: actions/cache@v2
            with:
                path: "{{ env.HOME }}/bin/unidoc.gz"
                key: "unidoc:${{ runner.os }}-${{ runner.arch }}/${{ inputs.unidoc-version }}"

        -   name: Download Unidoc
            shell: bash
            env:
                UNIDOC_BINARIES: $HOME/bin
                UNIDOC_PLATFORM: ${{ runner.os }}-${{ runner.arch }}
                UNIDOC_VERSION: ${{ inputs.unidoc-version }}
                UNIDOC_MIRROR: "https://static.swiftinit.org/unidoc"

            run: |
                mkdir -p $UNIDOC_BINARIES
                curl -L $UNIDOC_MIRROR/$UNIDOC_VERSION/$UNIDOC_PLATFORM/unidoc.gz \
                    -o $UNIDOC_BINARIES/unidoc.gz
                gzip -fdk $UNIDOC_BINARIES/unidoc.gz
                chmod +x $UNIDOC_BINARIES/unidoc
                echo "$UNIDOC_BINARIES" >> $GITHUB_PATH

        -   name: Check Unidoc
            shell: bash
            run: |
                unidoc --help
