name: "Unidoc install"
description: "Install Swift Unidoc"

inputs:
    unidoc-version:
        description: "The version of Unidoc to use"
        required: true
        default: "0.19.0"

runs:
    using: composite
    steps:
        -   name: Cache Unidoc
            id:   cache
            uses: actions/cache@v2
            with:
                path: "$HOME/unidoc/bin/unidoc.gz"
                key: "unidoc:${{ runner.os }}-${{ runner.arch }}/${{ inputs.unidoc-version }}"

        -   name: Download Unidoc
            shell: bash
            if: steps.cache.outputs.cache-hit != 'true'
            env:
                UNIDOC_PLATFORM: ${{ runner.os }}-${{ runner.arch }}
                UNIDOC_VERSION: ${{ inputs.unidoc-version }}
                UNIDOC_MIRROR: "https://static.swiftinit.org/unidoc"

            run: |
                mkdir -p $HOME/unidoc/bin
                curl -L $UNIDOC_MIRROR/$UNIDOC_VERSION/$UNIDOC_PLATFORM/unidoc.gz \
                    -o $HOME/unidoc/bin/unidoc.gz

        -   name: Install Unidoc
            shell: bash
            run: |
                mkdir -p $HOME/unidoc/bin
                gzip -fdk $HOME/unidoc/bin/unidoc.gz
                chmod +x $HOME/unidoc/bin/unidoc
                echo "$HOME/unidoc/bin" >> $GITHUB_PATH

        -   name: Check Unidoc
            shell: bash
            run: |
                cat $GITHUB_PATH
                unidoc --help
