name: "Unidoc install"
description: "Install Swift Unidoc"
branding:
    icon: check-circle
    color: purple
inputs:
    unidoc-version:
        description: "The version of Unidoc to use"
        required: false
        default: "latest"

runs:
    using: composite
    steps:
        -   name: Resolve Unidoc version
            id: version
            shell: bash
            env:
                GH_TOKEN: ${{ github.token }}
            run: |
                VERSION="${{ inputs.unidoc-version }}"

                if [ "$VERSION" = "latest" ]; then
                    VERSION=$(
                        gh api "repos/${GITHUB_REPOSITORY}/tags" --paginate --jq '.[].name' \
                        | grep -E '^[0-9]+\.[0-9]+\.[0-9]+' \
                        | sort -rV | head -n 1 \
                    )
                    if [ "$VERSION" = "null" ] || [ -z "$VERSION" ]; then
                        echo "Could not determine the latest Unidoc version from GitHub!"
                        exit 1
                    fi
                fi

                echo "version=$VERSION" >> $GITHUB_OUTPUT

        -   name: Create installation directory
            shell: bash
            run: |
                mkdir -p ~/unidoc/bin

        -   name: Cache Unidoc
            id:   cache
            uses: actions/cache@v4
            with:
                path: "~/unidoc/bin/unidoc.tar.gz"
                key: "unidoc:${{ runner.os }}-${{ runner.arch }}/${{ steps.version.outputs.version }}"

        -   name: Detect Platform
            shell: bash
            if: runner.os == 'Linux'
            run: |
                echo "UNIDOC_PLATFORM=Ubuntu-24.04-${{ runner.arch }}" >> $GITHUB_ENV

        -   name: Detect Platform
            shell: bash
            if: runner.os == 'macOS'
            run: |
                echo "UNIDOC_PLATFORM=${{ runner.os }}-${{ runner.arch }}" >> $GITHUB_ENV

        -   name: Download Unidoc
            shell: bash
            if: steps.cache.outputs.cache-hit != 'true'
            env:
                UNIDOC_VERSION: ${{ steps.resolve-version.outputs.version }}
                UNIDOC_MIRROR: "https://download.rarestype.com/unidoc"

            run: |
                curl -L $UNIDOC_MIRROR/$UNIDOC_VERSION/$UNIDOC_PLATFORM/unidoc.tar.gz \
                    -o ~/unidoc/bin/unidoc.tar.gz

        -   name: Install Unidoc
            shell: bash
            run: |
                tar -C ~/unidoc/bin/ -xf ~/unidoc/bin/unidoc.tar.gz
                echo "$HOME/unidoc/bin" >> $GITHUB_PATH

        -   name: Check Unidoc
            shell: bash
            run: |
                cat $GITHUB_PATH
                unidoc --version
                unidoc --help
