name: "Unidoc install"
description: "Install Swift Unidoc"

inputs:
    unidoc-version:
        description: "The version of Unidoc to use"
        required: false
        default: "0.19.2"

runs:
    using: composite
    steps:
        -   name: Create installation directory
            shell: bash
            run: |
                mkdir -p ~/unidoc/bin

        -   name: Cache Unidoc
            id:   cache
            uses: actions/cache@v2
            with:
                path: "~/unidoc/bin/unidoc.tar.gz"
                key: "unidoc:${{ runner.os }}-${{ runner.arch }}/${{ inputs.unidoc-version }}"

        -   name: Download Unidoc
            shell: bash
            if: steps.cache.outputs.cache-hit != 'true'
            env:
                UNIDOC_PLATFORM: ${{ runner.os }}-${{ runner.arch }}
                UNIDOC_VERSION: ${{ inputs.unidoc-version }}
                UNIDOC_MIRROR: "https://static.swiftinit.org/unidoc"

            run: |
                curl -L $UNIDOC_MIRROR/$UNIDOC_VERSION/$UNIDOC_PLATFORM/unidoc.tar.gz \
                    -o ~/unidoc/bin/unidoc.tar.gz

        -   name: Install Unidoc
            shell: bash
            run: |
                tar -C ~/unidoc/bin/ -xf ~/unidoc/bin/unidoc.tar.gz
                echo "$HOME/unidoc/bin" >> $GITHUB_PATH

        -   name: Check Unidoc
            shell: bash
            run: |
                cat $GITHUB_PATH
                unidoc --help
