name: self test

on:
    push:
        branches: [ master ]

    pull_request:
        branches: [ master ]

jobs:
    macos:
        runs-on: macos-15
        name: macOS

        steps:
            -   name: Install Unidoc
                uses: tayloraswift/swift-unidoc-action@master
                with:
                    unidoc-version: "master"

            -   name: Check Unidoc
                run: unidoc --help

    linux:
        runs-on: ubuntu-24.04
        name: Ubuntu 24.04

        steps:
            -   name: Install Unidoc
                uses: tayloraswift/swift-unidoc-action@master
                with:
                    unidoc-version: "master"

            -   name: Check Unidoc
                run: unidoc --help
